// Unpacks the design bundle into the app: fonts (latin subsets only), token logos, global CSS, and reference copies
// of the design's template, logic and mock-data module (design/extracted/, not committed).
//
//   node tools/extract-design.ts

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadBundle, logicOf, ROOT } from './design-bundle.ts';

const KEEP_SUBSETS = new Set(['latin', 'latin-ext', 'symbols2']);

const bundle = loadBundle();
const app = (p: string) => resolve(ROOT, 'app', p);
const write = (path: string, data: string | Buffer) => {
  mkdirSync(resolve(path, '..'), { recursive: true });
  writeFileSync(path, data);
};

const helmet = bundle.template.slice(bundle.template.indexOf('<helmet>'), bundle.template.indexOf('</helmet>'));
const styles = [...helmet.matchAll(/<style>([\s\S]*?)<\/style>/g)].map((m) => m[1] ?? '');
const fontCss = styles.find((s) => s.includes('@font-face')) ?? '';
const globalCss = styles.filter((s) => !s.includes('@font-face')).join('\n');

// Fonts: one file per uuid (the design reuses variable-font files across weights).
const faces: string[] = [];
const written = new Map<string, string>();
for (const m of fontCss.matchAll(/\/\* ([\w-]+) \*\/\s*@font-face \{([\s\S]*?)\}/g)) {
  const [, subset, body] = m as unknown as [string, string, string];
  if (!KEEP_SUBSETS.has(subset)) continue;
  const uuid = body.match(/url\("([^"]+)"\)/)?.[1];
  const family = body.match(/font-family: '([^']+)'/)?.[1];
  if (!uuid || !family) continue;
  let file = written.get(uuid);
  if (!file) {
    file = `${family.toLowerCase().replace(/\s+/g, '-')}-${subset}-${uuid.slice(0, 8)}.woff2`;
    write(app(`public/fonts/${file}`), bundle.asset(uuid).bytes);
    written.set(uuid, file);
  }
  faces.push(`/* ${subset} */\n@font-face {${body.replace(/url\("[^"]+"\)/, `url("/fonts/${file}")`)}}`);
}
write(app('src/styles/fonts.css'), `/* Generated by tools/extract-design.ts from design/ZAP.html */\n${faces.join('\n')}\n`);

// Global CSS. React serializes inline styles as "border: 1px solid …" (with a space), so the design's
// focus-ring selector gets a second spelling that matches.
const css = globalCss.replace(
  'label[style*="border:1px solid"]:focus-within,input[style*="border:1px solid"]:focus',
  'label[style*="border:1px solid"]:focus-within,input[style*="border:1px solid"]:focus,' +
    'label[style*="border: 1px solid"]:focus-within,input[style*="border: 1px solid"]:focus',
);
write(app('src/styles/design.css'), `/* Generated by tools/extract-design.ts from design/ZAP.html */\n${css}\n`);

// Logos for listed markets, USDC and the supported wallets only:
// L_logos_btc_png → /logos/btc.png, L_logos_solflare_icon_svg → /logos/solflare_icon.svg
const markets = JSON.parse(readFileSync(resolve(ROOT, 'config/markets.json'), 'utf8')) as { markets: { base: string }[] };
const wanted = new Set([...markets.markets.map((m) => m.base.toLowerCase()), 'usdc', 'phantom', 'backpack', 'solflare_icon']);
let logos = 0;
for (const [id, uuid] of Object.entries(bundle.resources)) {
  const m = id.match(/^L_logos_(.+)_(png|svg)$/);
  if (!m || !wanted.has(m[1] ?? '')) continue;
  write(app(`public/logos/${m[1]}.${m[2]}`), bundle.asset(uuid).bytes);
  logos++;
}

// Reference copies for porting (gitignored).
const ref = (p: string) => resolve(ROOT, 'design/extracted', p);
write(ref('template.html'), bundle.template);
write(ref('logic.js'), logicOf(bundle.template));
const keel = bundle.resources['keelData'];
if (keel) write(ref('keel-data.js'), bundle.asset(keel).bytes);

console.log(`fonts: ${written.size} files, ${faces.length} faces · logos: ${logos} · css: ${css.length} chars`);
